### ISSUE TITLE
Disabled components in Unity are not disabled in Urho3D .

### ISSUE THREAD

**Issue by elix22** [gleblebedev/Unity2Urho#7]
Disabled components in Unity are not disabled in Urho3D .
For example  , disabled “Mesh Renderer” in Unity  will still show the Static model in Urho3D.
The exported components are missing the “Is Enabled” attribute
Every disabled component should have the following attribute.

`<attribute name="Is Enabled" value="false" />`

**Comment by gleblebedev** [comment]
Fixed

**Comment by elix22** [comment]
Perfect
Thanks
